// Generated by gencpp from file myserv_msg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MYSERV_MSG_MESSAGE_ADDTWOINTS_H
#define MYSERV_MSG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <myserv_msg/AddTwoIntsRequest.h>
#include <myserv_msg/AddTwoIntsResponse.h>


namespace myserv_msg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace myserv_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myserv_msg::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::myserv_msg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::myserv_msg::AddTwoInts > {
  static const char* value()
  {
    return "myserv_msg/AddTwoInts";
  }

  static const char* value(const ::myserv_msg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::myserv_msg::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::myserv_msg::AddTwoInts > 
template<>
struct MD5Sum< ::myserv_msg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myserv_msg::AddTwoInts >::value();
  }
  static const char* value(const ::myserv_msg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myserv_msg::AddTwoIntsRequest> should match 
// service_traits::DataType< ::myserv_msg::AddTwoInts > 
template<>
struct DataType< ::myserv_msg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::myserv_msg::AddTwoInts >::value();
  }
  static const char* value(const ::myserv_msg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myserv_msg::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::myserv_msg::AddTwoInts > 
template<>
struct MD5Sum< ::myserv_msg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myserv_msg::AddTwoInts >::value();
  }
  static const char* value(const ::myserv_msg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myserv_msg::AddTwoIntsResponse> should match 
// service_traits::DataType< ::myserv_msg::AddTwoInts > 
template<>
struct DataType< ::myserv_msg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::myserv_msg::AddTwoInts >::value();
  }
  static const char* value(const ::myserv_msg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYSERV_MSG_MESSAGE_ADDTWOINTS_H
