// Generated by gencpp from file myserv_msg/num.msg
// DO NOT EDIT!


#ifndef MYSERV_MSG_MESSAGE_NUM_H
#define MYSERV_MSG_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myserv_msg
{
template <class ContainerAllocator>
struct num_
{
  typedef num_<ContainerAllocator> Type;

  num_()
    : num(0)  {
    }
  num_(const ContainerAllocator& _alloc)
    : num(0)  {
    }



   typedef int64_t _num_type;
  _num_type num;




  typedef boost::shared_ptr< ::myserv_msg::num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myserv_msg::num_<ContainerAllocator> const> ConstPtr;

}; // struct num_

typedef ::myserv_msg::num_<std::allocator<void> > num;

typedef boost::shared_ptr< ::myserv_msg::num > numPtr;
typedef boost::shared_ptr< ::myserv_msg::num const> numConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myserv_msg::num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myserv_msg::num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myserv_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'myserv_msg': ['/home/joseph/workspace_catkin/src/myserv_msg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myserv_msg::num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myserv_msg::num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myserv_msg::num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myserv_msg::num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myserv_msg::num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myserv_msg::num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myserv_msg::num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57d3c40ec3ac3754af76a83e6e73127a";
  }

  static const char* value(const ::myserv_msg::num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57d3c40ec3ac3754ULL;
  static const uint64_t static_value2 = 0xaf76a83e6e73127aULL;
};

template<class ContainerAllocator>
struct DataType< ::myserv_msg::num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myserv_msg/num";
  }

  static const char* value(const ::myserv_msg::num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myserv_msg::num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n\
";
  }

  static const char* value(const ::myserv_msg::num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myserv_msg::num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myserv_msg::num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myserv_msg::num_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYSERV_MSG_MESSAGE_NUM_H
