set(_CATKIN_CURRENT_PACKAGE "rosapi")
set(rosapi_MAINTAINER "Russell Toris <rctoris@wpi.edu>, Jihoon Lee <jihoonlee.in@gmail.com>")
set(rosapi_DEPRECATED "")
set(rosapi_VERSION "0.7.13")
set(rosapi_BUILD_DEPENDS "rospy" "message_generation")
set(rosapi_RUN_DEPENDS "rosbridge_library" "rospy" "rosnode" "rosgraph" "message_runtime")
set(rosapi_BUILDTOOL_DEPENDS "catkin")